Add `third-party/latex3`

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,7 +16,29 @@ jobs:
         uses: actions/checkout@v6
         with:
           submodules: true
+          fetch-depth: 500  # Historically, the maximum number of commits between two tags in the latex3 repository is ~300.
+          fetch-tags: true
+      - name: Install TeX Live
+        uses: zauguin/install-texlive@v4
+        with:
+          cache: false
+          packages: |
+            l3kernel
+      - name: Check latex3
+        run: |
+          set -e
+          cd third-party/latex3
+          CURRENT_RELEASE="$(git describe --tags --abbrev=0)"
+          REMOTE_RELEASE="$(sed -rn '/^\\def\\ExplFileDate/s/.*([0-9]{4}-[0-9]{2}-[0-9]{2}).*/\1/p' "$(kpsewhich expl3-code.tex)")"
+          if [ "$CURRENT_RELEASE" '<' "$REMOTE_RELEASE" ]
+          then
+            printf 'Submodule "third-party/latex3" (%s) is not up-to-date with the latest TeX Live (%s).\n' "$CURRENT_RELEASE" "$REMOTE_RELEASE"
+            exit 1
+          else
+            printf 'Submodule "third-party/latex3" is up-to-date with the latest TeX Live.\n'
+          fi
       - name: Check lua-toml
+        if: success() || steps.luacheck.outcome == 'failure'  # Check lua-toml even if checking latex3 failed.
         run: |
           set -e
           cd third-party/lua-toml
